main: io.github.aleksandarharalanov.safepets.SafePets
version: 1.0.1
name: SafePets
author: Beezle
website: github.com/AleksandarHaralanov/SafePets
description: Prevents players from harming others' pets.

permissions:
  safepets.bypass:
    description: Allows player to bypass SafePets protection.
    default: op